sudo: required

services:
  - docker

before_install:
  - docker pull rocker/verse:3.5

script:
  - docker run --rm -v $(pwd):/home/rstudio --user root rocker/verse:3.5 r -e "devtools::install_github('rstudio/rticles'); rmarkdown::render('/home/rstudio/how-to-read-a-research-compendium.Rmd', output_dir = '/home/rstudio/pages')"
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: "ja3xiNEMPpHGShCtum5a+g5kmQaYWcxwMNF4gxqY3H0rzllzX6n9ReQmRD/SH7BAhF4xtL+cw8DrflGWuyFWJAx8UrT2c5JNtFQdp0ZzC1TVEB2m4HFxqL0FFf9P5jL8dBkN25Ms4u/gDt5vUUHzMFg6adt0c7K6SZ9etrvO7Ae/7IeZUtCvNsFwFtj3HfVENzuxkCZLac3pseZGaN4CLZ4LQzomXcFmQ5GNtoZQBeLTjIUrjPxML2BF/tk0o9tKexC+E7cprImJgywk05a67Hv1gUgobbqlRr8ndxB4gStSQtMmcci1NshK8jE7OSyKYeuMwnedNfHVm8YSB6fbKtbnUNKhf96L4UYQEaaegfwbHWAhjWYlovn68xe5rcyhWxUgr/RXClv/pHoxZYcq8ycuQAGmZt2YhzNzqGWfalmdYx/ZBwZm/ty8K5ZLz562LbiQ+xPGd36vEwEEaFXnBbzfdfza64kSb+eG0zb/41+g671s9faNvpqGoyr4HgSW3hR1lgGNA0LS+I1YwzCjqW3GYWautS1pm9XfGgz/XWiSoocT1s8Drg8+ZS+szm9XWQa2756eLnPvkfz7ALv5uXC9sVLAMsl8tkmYKJ7usc5ceYLpMdYrGD9jO8h9CjNf/hxB/QyR6/0n9bceAshRcPaw1ZJ6oRoCGiQsIAWIHAw="
  local_dir: pages
  on:
    branch: master